# Generated by Django 5.2 on 2025-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Turf',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
