# Generated by Django 5.2 on 2025-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscapp', '0002_book_turf_alter_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
