# Generated by Django 5.2 on 2025-04-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscapp', '0004_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='uid',
            new_name='id',
        ),
    ]
