# Generated by Django 5.2 on 2025-08-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscapp', '0005_rename_uid_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
