web: gunicorn msc.wsgi
# Virtual environments
venv/
.venv/

# Python cache / compiled files
__pycache__/
*.pyc
*.pyo
*.pyd

# IDE / Editor settings
.idea/
.vscode/

# OS files
.DS_Store

# Django / Database files
*.sqlite3
db.sqlite3

# Logs
*.log

# Environment variables
.env
